version: '3'
services:
  pupil_db:
    container_name: pupil_db
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Password@123
  pupil_web:
    container_name: pupil_web
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - RAILS_ENV=development
      - DB_HOST=pupil_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=Password@123
      - DB_NAME=pupil_db
      - DB_NAME_TEST=pupilfirst_test
    depends_on:
      - pupil_db
    tty: true
    stdin_open: true

volumes:
  db:
    driver: local
